algo = input('Digite algo: ')
print(f'O tipo primitivo é {type(algo)}')
print('Só tem espaços? ', algo.isspace())
print('È um numero? ', algo.isnumeric())
print('È alfabetico? ', algo.isalpha())
print('È alfanumerico? ', algo.isalnum())
print('Está em maiusculas? ', algo.isupper())
print('Está em minuculas? ', algo.islower())
print('Capitalizada? ', algo.istitle())
